#!/bin/bash

echo ""
echo "Installing required Python packages"
source $OPENSHIFT_HOMEDIR/python/virtenv/bin/activate
pip2 install --no-cache-dir --upgrade pip
pip2 install --no-cache-dir -r $OPENSHIFT_REPO_DIR/requirements.txt
